# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

EMGQ_measonly <- function(w, v, Y1star, Y2star, Covariates, isY2in, CovMis2, R, beta1, beta2, gamma, sigma, sigma_e, sigma_g) {
    .Call('_GeneErrorMis_EMGQ_measonly', PACKAGE = 'GeneErrorMis', w, v, Y1star, Y2star, Covariates, isY2in, CovMis2, R, beta1, beta2, gamma, sigma, sigma_e, sigma_g)
}

EMGQ_misconly <- function(w, v, Y1star, Y2star, Covariates, isY2in, CovMis2, R, beta1, beta2, alpha1, alpha0, sigma, sigma_g) {
    .Call('_GeneErrorMis_EMGQ_misconly', PACKAGE = 'GeneErrorMis', w, v, Y1star, Y2star, Covariates, isY2in, CovMis2, R, beta1, beta2, alpha1, alpha0, sigma, sigma_g)
}

EMGQ_nullmeas_ci <- function(w, v, Y1star, Y2star, Covariates, isY2in, CovMis2, R, beta1, beta2, lambda, gamma, alpha1, alpha0, sigma, sigma_e, sigma_g) {
    .Call('_GeneErrorMis_EMGQ_nullmeas_ci', PACKAGE = 'GeneErrorMis', w, v, Y1star, Y2star, Covariates, isY2in, CovMis2, R, beta1, beta2, lambda, gamma, alpha1, alpha0, sigma, sigma_e, sigma_g)
}

EMGQ_nullmeas_ci_nlam <- function(w, v, Y1star, Y2star, Covariates, isY2in, CovMis2, R, beta1, beta2, gamma, alpha1, alpha0, sigma, sigma_e, sigma_g) {
    .Call('_GeneErrorMis_EMGQ_nullmeas_ci_nlam', PACKAGE = 'GeneErrorMis', w, v, Y1star, Y2star, Covariates, isY2in, CovMis2, R, beta1, beta2, gamma, alpha1, alpha0, sigma, sigma_e, sigma_g)
}

EMGQ_twin_nlam <- function(w, v, Y1star, Y2star, Covariates, isY2in, CovMis2, rho, beta1, beta2, gamma, alpha1, alpha0, sigma, sigma_e, sigma_g) {
    .Call('_GeneErrorMis_EMGQ_twin_nlam', PACKAGE = 'GeneErrorMis', w, v, Y1star, Y2star, Covariates, isY2in, CovMis2, rho, beta1, beta2, gamma, alpha1, alpha0, sigma, sigma_e, sigma_g)
}

GEE_GAMMAIns <- function(Y1star, Y2star, DesignMatrix1, DesignMatrix2, beta1, beta2, xi, sigma) {
    .Call('_GeneErrorMis_GEE_GAMMAIns', PACKAGE = 'GeneErrorMis', Y1star, Y2star, DesignMatrix1, DesignMatrix2, beta1, beta2, xi, sigma)
}

GEE_GAMMAInsEV0 <- function(Y1star, Y2star, Y1, Y2, CovMis1, CovMis2, ncov1, ncov2, gamma1, gamma, alpha1, alpha0, sigma_e, fixgamma1, fixgamma, fixsigma_e, fixalpha1, fixalpha0) {
    .Call('_GeneErrorMis_GEE_GAMMAInsEV0', PACKAGE = 'GeneErrorMis', Y1star, Y2star, Y1, Y2, CovMis1, CovMis2, ncov1, ncov2, gamma1, gamma, alpha1, alpha0, sigma_e, fixgamma1, fixgamma, fixsigma_e, fixalpha1, fixalpha0)
}

GEE_GAMMAInsEVI <- function(Y1star, Y2star, DesignMatrix1, DesignMatrix2, CovMis1, CovMis2, beta1, beta2, xi, sigma, gamma1, gamma, alpha1, alpha0, sigma_e, fixgamma1, fixgamma, fixsigma_e, fixalpha1, fixalpha0) {
    .Call('_GeneErrorMis_GEE_GAMMAInsEVI', PACKAGE = 'GeneErrorMis', Y1star, Y2star, DesignMatrix1, DesignMatrix2, CovMis1, CovMis2, beta1, beta2, xi, sigma, gamma1, gamma, alpha1, alpha0, sigma_e, fixgamma1, fixgamma, fixsigma_e, fixalpha1, fixalpha0)
}

GEE_GAMMAInsIV0 <- function(Y1star, Y2star, Y1, Y2, CovMis1, CovMis2, ValidationMatrix1, ValidationMatrix2, beta1, beta2, xi, sigma, gamma1, gamma, alpha1, alpha0, sigma_e, fixgamma1, fixgamma, fixsigma_e, fixalpha1, fixalpha0) {
    .Call('_GeneErrorMis_GEE_GAMMAInsIV0', PACKAGE = 'GeneErrorMis', Y1star, Y2star, Y1, Y2, CovMis1, CovMis2, ValidationMatrix1, ValidationMatrix2, beta1, beta2, xi, sigma, gamma1, gamma, alpha1, alpha0, sigma_e, fixgamma1, fixgamma, fixsigma_e, fixalpha1, fixalpha0)
}

GEE_GAMMAInsIVI <- function(Y1star, Y2star, DesignMatrix1, DesignMatrix2, CovMis1, CovMis2, beta1, beta2, xi, sigma, gamma1, gamma, alpha1, alpha0, sigma_e, fixgamma1, fixgamma, fixsigma_e, fixalpha1, fixalpha0) {
    .Call('_GeneErrorMis_GEE_GAMMAInsIVI', PACKAGE = 'GeneErrorMis', Y1star, Y2star, DesignMatrix1, DesignMatrix2, CovMis1, CovMis2, beta1, beta2, xi, sigma, gamma1, gamma, alpha1, alpha0, sigma_e, fixgamma1, fixgamma, fixsigma_e, fixalpha1, fixalpha0)
}

GEE_SIGMAIns <- function(Y1star, Y2star, DesignMatrix1, DesignMatrix2, CovMis1, CovMis2, beta1, beta2, xi, sigma, gamma1, gamma, alpha1, alpha0, sigma_e) {
    .Call('_GeneErrorMis_GEE_SIGMAIns', PACKAGE = 'GeneErrorMis', Y1star, Y2star, DesignMatrix1, DesignMatrix2, CovMis1, CovMis2, beta1, beta2, xi, sigma, gamma1, gamma, alpha1, alpha0, sigma_e)
}

GEE_SIGMAInsEV0 <- function(Y1star, Y2star, Y1, Y2, CovMis1, CovMis2, ncov1, ncov2, gamma1, gamma, alpha1, alpha0, sigma_e, fixgamma1, fixgamma, fixsigma_e, fixalpha1, fixalpha0) {
    .Call('_GeneErrorMis_GEE_SIGMAInsEV0', PACKAGE = 'GeneErrorMis', Y1star, Y2star, Y1, Y2, CovMis1, CovMis2, ncov1, ncov2, gamma1, gamma, alpha1, alpha0, sigma_e, fixgamma1, fixgamma, fixsigma_e, fixalpha1, fixalpha0)
}

GEE_SIGMAInsEVI <- function(Y1star, Y2star, DesignMatrix1, DesignMatrix2, CovMis1, CovMis2, beta1, beta2, xi, sigma, gamma1, gamma, alpha1, alpha0, sigma_e, fixgamma1, fixgamma, fixsigma_e, fixalpha1, fixalpha0) {
    .Call('_GeneErrorMis_GEE_SIGMAInsEVI', PACKAGE = 'GeneErrorMis', Y1star, Y2star, DesignMatrix1, DesignMatrix2, CovMis1, CovMis2, beta1, beta2, xi, sigma, gamma1, gamma, alpha1, alpha0, sigma_e, fixgamma1, fixgamma, fixsigma_e, fixalpha1, fixalpha0)
}

GEE_SIGMAInsIV0 <- function(Y1star, Y2star, Y1, Y2, ValidationMatrix1, ValidationMatrix2, CovMis1, CovMis2, beta1, beta2, xi, sigma, gamma1, gamma, alpha1, alpha0, sigma_e, fixgamma1, fixgamma, fixsigma_e, fixalpha1, fixalpha0) {
    .Call('_GeneErrorMis_GEE_SIGMAInsIV0', PACKAGE = 'GeneErrorMis', Y1star, Y2star, Y1, Y2, ValidationMatrix1, ValidationMatrix2, CovMis1, CovMis2, beta1, beta2, xi, sigma, gamma1, gamma, alpha1, alpha0, sigma_e, fixgamma1, fixgamma, fixsigma_e, fixalpha1, fixalpha0)
}

GEE_SIGMAInsIVI <- function(Y1star, Y2star, DesignMatrix1, DesignMatrix2, CovMis1, CovMis2, beta1, beta2, xi, sigma, gamma1, gamma, alpha1, alpha0, sigma_e, fixgamma1, fixgamma, fixsigma_e, fixalpha1, fixalpha0) {
    .Call('_GeneErrorMis_GEE_SIGMAInsIVI', PACKAGE = 'GeneErrorMis', Y1star, Y2star, DesignMatrix1, DesignMatrix2, CovMis1, CovMis2, beta1, beta2, xi, sigma, gamma1, gamma, alpha1, alpha0, sigma_e, fixgamma1, fixgamma, fixsigma_e, fixalpha1, fixalpha0)
}

GEE_UfuncIns <- function(Y1star, Y2star, DesignMatrix1, DesignMatrix2, CovMis1, CovMis2, beta1, beta2, xi, sigma, gamma1, gamma, alpha1, alpha0, sigma_e) {
    .Call('_GeneErrorMis_GEE_UfuncIns', PACKAGE = 'GeneErrorMis', Y1star, Y2star, DesignMatrix1, DesignMatrix2, CovMis1, CovMis2, beta1, beta2, xi, sigma, gamma1, gamma, alpha1, alpha0, sigma_e)
}

GEE_UfuncInsIV <- function(Y1star, Y2star, Y1, Y2, DesignMatrix1, DesignMatrix2, ValidationMatrix1, ValidationMatrix2, CovMis1, CovMis2, beta1, beta2, xi, sigma, gamma1, gamma, alpha1, alpha0, sigma_e) {
    .Call('_GeneErrorMis_GEE_UfuncInsIV', PACKAGE = 'GeneErrorMis', Y1star, Y2star, Y1, Y2, DesignMatrix1, DesignMatrix2, ValidationMatrix1, ValidationMatrix2, CovMis1, CovMis2, beta1, beta2, xi, sigma, gamma1, gamma, alpha1, alpha0, sigma_e)
}

GEE_UfuncInsIVWeight <- function(Y1star, Y2star, Y1, Y2, DesignMatrix1, DesignMatrix2, ValidationMatrix1, ValidationMatrix2, CovMis1, CovMis2, Weight, beta1, beta2, xi, sigma, gamma1, gamma, alpha1, alpha0, sigma_e) {
    .Call('_GeneErrorMis_GEE_UfuncInsIVWeight', PACKAGE = 'GeneErrorMis', Y1star, Y2star, Y1, Y2, DesignMatrix1, DesignMatrix2, ValidationMatrix1, ValidationMatrix2, CovMis1, CovMis2, Weight, beta1, beta2, xi, sigma, gamma1, gamma, alpha1, alpha0, sigma_e)
}

IL_infomat_measonly <- function(w, v, Y1star, Y2star, Covariates, isY2in, CovMis2, R, beta1, beta2, gamma, sigma, sigma_e, sigma_g) {
    .Call('_GeneErrorMis_IL_infomat_measonly', PACKAGE = 'GeneErrorMis', w, v, Y1star, Y2star, Covariates, isY2in, CovMis2, R, beta1, beta2, gamma, sigma, sigma_e, sigma_g)
}

IL_infomat_misconly <- function(w, v, Y1star, Y2star, Covariates, isY2in, CovMis2, R, beta1, beta2, alpha1, alpha0, sigma, sigma_g) {
    .Call('_GeneErrorMis_IL_infomat_misconly', PACKAGE = 'GeneErrorMis', w, v, Y1star, Y2star, Covariates, isY2in, CovMis2, R, beta1, beta2, alpha1, alpha0, sigma, sigma_g)
}

IL_infomat_noerror <- function(w, v, Y1, Y2, Covariates, R, beta1, beta2, sigma, sigma_g) {
    .Call('_GeneErrorMis_IL_infomat_noerror', PACKAGE = 'GeneErrorMis', w, v, Y1, Y2, Covariates, R, beta1, beta2, sigma, sigma_g)
}

IL_infomat_nullmeas_ci <- function(w, v, Y1star, Y2star, Covariates, isY2in, CovMis2, R, beta1, beta2, lambda, gamma, alpha1, alpha0, sigma, sigma_e, sigma_g) {
    .Call('_GeneErrorMis_IL_infomat_nullmeas_ci', PACKAGE = 'GeneErrorMis', w, v, Y1star, Y2star, Covariates, isY2in, CovMis2, R, beta1, beta2, lambda, gamma, alpha1, alpha0, sigma, sigma_e, sigma_g)
}

IL_infomat_nullmeas_ci_nlam <- function(w, v, Y1star, Y2star, Covariates, isY2in, CovMis2, R, beta1, beta2, gamma, alpha1, alpha0, sigma, sigma_e, sigma_g) {
    .Call('_GeneErrorMis_IL_infomat_nullmeas_ci_nlam', PACKAGE = 'GeneErrorMis', w, v, Y1star, Y2star, Covariates, isY2in, CovMis2, R, beta1, beta2, gamma, alpha1, alpha0, sigma, sigma_e, sigma_g)
}

IL_infomat_nullmeas_ci_ulam <- function(w, v, Y1star, Y2star, Covariates, isY2in, CovMis2, R, beta1, beta2, lambda, gamma, alpha1, alpha0, sigma, sigma_e, sigma_g) {
    .Call('_GeneErrorMis_IL_infomat_nullmeas_ci_ulam', PACKAGE = 'GeneErrorMis', w, v, Y1star, Y2star, Covariates, isY2in, CovMis2, R, beta1, beta2, lambda, gamma, alpha1, alpha0, sigma, sigma_e, sigma_g)
}

IL_infomat_twin <- function(w, v, Y1star, Y2star, Covariates, isY2in, CovMis2, rho, beta1, beta2, gamma, alpha1, alpha0, sigma, sigma_e, sigma_g) {
    .Call('_GeneErrorMis_IL_infomat_twin', PACKAGE = 'GeneErrorMis', w, v, Y1star, Y2star, Covariates, isY2in, CovMis2, rho, beta1, beta2, gamma, alpha1, alpha0, sigma, sigma_e, sigma_g)
}

IL_infomat_twin_measonly <- function(w, v, Y1star, Y2star, Covariates, isY2in, CovMis2, rho, beta1, beta2, gamma, sigma, sigma_e, sigma_g) {
    .Call('_GeneErrorMis_IL_infomat_twin_measonly', PACKAGE = 'GeneErrorMis', w, v, Y1star, Y2star, Covariates, isY2in, CovMis2, rho, beta1, beta2, gamma, sigma, sigma_e, sigma_g)
}

IL_infomat_twin_misconly <- function(w, v, Y1star, Y2star, Covariates, isY2in, CovMis2, rho, beta1, beta2, alpha1, alpha0, sigma, sigma_g) {
    .Call('_GeneErrorMis_IL_infomat_twin_misconly', PACKAGE = 'GeneErrorMis', w, v, Y1star, Y2star, Covariates, isY2in, CovMis2, rho, beta1, beta2, alpha1, alpha0, sigma, sigma_g)
}

IL_score_measonly <- function(w, v, Y1star, Y2star, Covariates, isY2in, CovMis2, R, beta1, beta2, gamma, sigma, sigma_e, sigma_g) {
    .Call('_GeneErrorMis_IL_score_measonly', PACKAGE = 'GeneErrorMis', w, v, Y1star, Y2star, Covariates, isY2in, CovMis2, R, beta1, beta2, gamma, sigma, sigma_e, sigma_g)
}

IL_score_misconly <- function(w, v, Y1star, Y2star, Covariates, isY2in, CovMis2, R, beta1, beta2, alpha1, alpha0, sigma, sigma_g) {
    .Call('_GeneErrorMis_IL_score_misconly', PACKAGE = 'GeneErrorMis', w, v, Y1star, Y2star, Covariates, isY2in, CovMis2, R, beta1, beta2, alpha1, alpha0, sigma, sigma_g)
}

IL_score_noerror <- function(w, v, Y1, Y2, Covariates, R, beta1, beta2, sigma, sigma_g) {
    .Call('_GeneErrorMis_IL_score_noerror', PACKAGE = 'GeneErrorMis', w, v, Y1, Y2, Covariates, R, beta1, beta2, sigma, sigma_g)
}

IL_score_nullmeas_ci <- function(w, v, Y1star, Y2star, Covariates, isY2in, CovMis2, R, beta1, beta2, lambda, gamma, alpha1, alpha0, sigma, sigma_e, sigma_g) {
    .Call('_GeneErrorMis_IL_score_nullmeas_ci', PACKAGE = 'GeneErrorMis', w, v, Y1star, Y2star, Covariates, isY2in, CovMis2, R, beta1, beta2, lambda, gamma, alpha1, alpha0, sigma, sigma_e, sigma_g)
}

IL_score_nullmeas_ci_nlam <- function(w, v, Y1star, Y2star, Covariates, isY2in, CovMis2, R, beta1, beta2, gamma, alpha1, alpha0, sigma, sigma_e, sigma_g) {
    .Call('_GeneErrorMis_IL_score_nullmeas_ci_nlam', PACKAGE = 'GeneErrorMis', w, v, Y1star, Y2star, Covariates, isY2in, CovMis2, R, beta1, beta2, gamma, alpha1, alpha0, sigma, sigma_e, sigma_g)
}

IL_score_nullmeas_ci_ulam <- function(w, v, Y1star, Y2star, Covariates, isY2in, CovMis2, R, beta1, beta2, lambda, gamma, alpha1, alpha0, sigma, sigma_e, sigma_g) {
    .Call('_GeneErrorMis_IL_score_nullmeas_ci_ulam', PACKAGE = 'GeneErrorMis', w, v, Y1star, Y2star, Covariates, isY2in, CovMis2, R, beta1, beta2, lambda, gamma, alpha1, alpha0, sigma, sigma_e, sigma_g)
}

IL_score_twin <- function(w, v, Y1star, Y2star, Covariates, isY2in, CovMis2, rho, beta1, beta2, gamma, alpha1, alpha0, sigma, sigma_e, sigma_g) {
    .Call('_GeneErrorMis_IL_score_twin', PACKAGE = 'GeneErrorMis', w, v, Y1star, Y2star, Covariates, isY2in, CovMis2, rho, beta1, beta2, gamma, alpha1, alpha0, sigma, sigma_e, sigma_g)
}

IL_score_twin_measonly <- function(w, v, Y1star, Y2star, Covariates, isY2in, CovMis2, rho, beta1, beta2, gamma, sigma, sigma_e, sigma_g) {
    .Call('_GeneErrorMis_IL_score_twin_measonly', PACKAGE = 'GeneErrorMis', w, v, Y1star, Y2star, Covariates, isY2in, CovMis2, rho, beta1, beta2, gamma, sigma, sigma_e, sigma_g)
}

IL_score_twin_misconly <- function(w, v, Y1star, Y2star, Covariates, isY2in, CovMis2, rho, beta1, beta2, alpha1, alpha0, sigma, sigma_g) {
    .Call('_GeneErrorMis_IL_score_twin_misconly', PACKAGE = 'GeneErrorMis', w, v, Y1star, Y2star, Covariates, isY2in, CovMis2, rho, beta1, beta2, alpha1, alpha0, sigma, sigma_g)
}

logLik_GQapprox_measonly <- function(w, v, Y1star, Y2star, Covariates, isY2in, CovMis2, R, beta1, beta2, gamma, sigma, sigma_e, sigma_g) {
    .Call('_GeneErrorMis_logLik_GQapprox_measonly', PACKAGE = 'GeneErrorMis', w, v, Y1star, Y2star, Covariates, isY2in, CovMis2, R, beta1, beta2, gamma, sigma, sigma_e, sigma_g)
}

logLik_GQapprox_misconly <- function(w, v, Y1star, Y2star, Covariates, isY2in, CovMis2, R, beta1, beta2, alpha1, alpha0, sigma, sigma_g) {
    .Call('_GeneErrorMis_logLik_GQapprox_misconly', PACKAGE = 'GeneErrorMis', w, v, Y1star, Y2star, Covariates, isY2in, CovMis2, R, beta1, beta2, alpha1, alpha0, sigma, sigma_g)
}

logLik_GQapprox_noerror <- function(w, v, Y1, Y2, Covariates, R, beta1, beta2, sigma, sigma_g) {
    .Call('_GeneErrorMis_logLik_GQapprox_noerror', PACKAGE = 'GeneErrorMis', w, v, Y1, Y2, Covariates, R, beta1, beta2, sigma, sigma_g)
}

logLik_GQapprox_nullmeas_ci <- function(w, v, Y1star, Y2star, Covariates, isY2in, CovMis2, R, beta1, beta2, lambda, gamma, alpha1, alpha0, sigma, sigma_e, sigma_g) {
    .Call('_GeneErrorMis_logLik_GQapprox_nullmeas_ci', PACKAGE = 'GeneErrorMis', w, v, Y1star, Y2star, Covariates, isY2in, CovMis2, R, beta1, beta2, lambda, gamma, alpha1, alpha0, sigma, sigma_e, sigma_g)
}

logLik_GQapprox_nullmeas_ci_nlam <- function(w, v, Y1star, Y2star, Covariates, isY2in, CovMis2, R, beta1, beta2, gamma, alpha1, alpha0, sigma, sigma_e, sigma_g) {
    .Call('_GeneErrorMis_logLik_GQapprox_nullmeas_ci_nlam', PACKAGE = 'GeneErrorMis', w, v, Y1star, Y2star, Covariates, isY2in, CovMis2, R, beta1, beta2, gamma, alpha1, alpha0, sigma, sigma_e, sigma_g)
}

logLik_GQapprox_nullmeas_ci_ulam <- function(w, v, Y1star, Y2star, Covariates, isY2in, CovMis2, R, beta1, beta2, lambda, gamma, alpha1, alpha0, sigma, sigma_e, sigma_g) {
    .Call('_GeneErrorMis_logLik_GQapprox_nullmeas_ci_ulam', PACKAGE = 'GeneErrorMis', w, v, Y1star, Y2star, Covariates, isY2in, CovMis2, R, beta1, beta2, lambda, gamma, alpha1, alpha0, sigma, sigma_e, sigma_g)
}

logLik_twin_measonly <- function(w, v, Y1star, Y2star, Covariates, isY2in, CovMis2, rho, beta1, beta2, gamma, sigma, sigma_e, sigma_g) {
    .Call('_GeneErrorMis_logLik_twin_measonly', PACKAGE = 'GeneErrorMis', w, v, Y1star, Y2star, Covariates, isY2in, CovMis2, rho, beta1, beta2, gamma, sigma, sigma_e, sigma_g)
}

logLik_twin_misconly <- function(w, v, Y1star, Y2star, Covariates, isY2in, CovMis2, rho, beta1, beta2, alpha1, alpha0, sigma, sigma_g) {
    .Call('_GeneErrorMis_logLik_twin_misconly', PACKAGE = 'GeneErrorMis', w, v, Y1star, Y2star, Covariates, isY2in, CovMis2, rho, beta1, beta2, alpha1, alpha0, sigma, sigma_g)
}

logLik_twin_nlam <- function(w, v, Y1star, Y2star, Covariates, isY2in, CovMis2, rho, beta1, beta2, gamma, alpha1, alpha0, sigma, sigma_e, sigma_g) {
    .Call('_GeneErrorMis_logLik_twin_nlam', PACKAGE = 'GeneErrorMis', w, v, Y1star, Y2star, Covariates, isY2in, CovMis2, rho, beta1, beta2, gamma, alpha1, alpha0, sigma, sigma_e, sigma_g)
}

logLikelihood_indep_c <- function(u, random1, random2, Y1star, Y2star, Covariates, CovMea1, isY2in, CovMis2, beta1, beta2, lambda, gamma, alpha1, alpha0, sigma, sigma_e) {
    .Call('_GeneErrorMis_logLikelihood_indep_c', PACKAGE = 'GeneErrorMis', u, random1, random2, Y1star, Y2star, Covariates, CovMea1, isY2in, CovMis2, beta1, beta2, lambda, gamma, alpha1, alpha0, sigma, sigma_e)
}

logLikelihood_indep_nullmeas_c <- function(u, random1, random2, Y1star, Y2star, Covariates, isY2in, CovMis2, beta1, beta2, lambda, gamma, alpha1, alpha0, sigma, sigma_e) {
    .Call('_GeneErrorMis_logLikelihood_indep_nullmeas_c', PACKAGE = 'GeneErrorMis', u, random1, random2, Y1star, Y2star, Covariates, isY2in, CovMis2, beta1, beta2, lambda, gamma, alpha1, alpha0, sigma, sigma_e)
}

logLikelihood_indep_nullmeas_cPar <- function(u, random1, random2, Y1star, Y2star, Covariates, isY2in, CovMis2, beta1, beta2, lambda, gamma, alpha1, alpha0, sigma, sigma_e) {
    .Call('_GeneErrorMis_logLikelihood_indep_nullmeas_cPar', PACKAGE = 'GeneErrorMis', u, random1, random2, Y1star, Y2star, Covariates, isY2in, CovMis2, beta1, beta2, lambda, gamma, alpha1, alpha0, sigma, sigma_e)
}

ZI_GenerateAlphaMNMetro <- function(Par, Y, Z, Covar, propsigma, priormu, priorSigmas) {
    .Call('_GeneErrorMis_ZI_GenerateAlphaMNMetro', PACKAGE = 'GeneErrorMis', Par, Y, Z, Covar, propsigma, priormu, priorSigmas)
}

ZI_GenerateBetaMetro <- function(Par, U, Covar, propsigma, priorgamma) {
    .Call('_GeneErrorMis_ZI_GenerateBetaMetro', PACKAGE = 'GeneErrorMis', Par, U, Covar, propsigma, priorgamma)
}

ZI_GenerateBigJoint <- function(Yistar, Ui1bound, Ui2bound, mu1i, mu2i, muZplusi, muZminusi) {
    .Call('_GeneErrorMis_ZI_GenerateBigJoint', PACKAGE = 'GeneErrorMis', Yistar, Ui1bound, Ui2bound, mu1i, mu2i, muZplusi, muZminusi)
}

ZI_GenerateJoint <- function(Yistar, minusbound, phii, mu2i, muZplusi, muZminusi) {
    .Call('_GeneErrorMis_ZI_GenerateJoint', PACKAGE = 'GeneErrorMis', Yistar, minusbound, phii, mu2i, muZplusi, muZminusi)
}

ZI_GeneratePoiPar_Binary <- function(Par, covariates, Outcome, priorgamma) {
    .Call('_GeneErrorMis_ZI_GeneratePoiPar_Binary', PACKAGE = 'GeneErrorMis', Par, covariates, Outcome, priorgamma)
}

ZI_GenerateU1 <- function(Y, U2, mu1) {
    .Call('_GeneErrorMis_ZI_GenerateU1', PACKAGE = 'GeneErrorMis', Y, U2, mu1)
}

ZI_GenerateU2 <- function(Y, U1, mu2) {
    .Call('_GeneErrorMis_ZI_GenerateU2', PACKAGE = 'GeneErrorMis', Y, U1, mu2)
}

ZI_GenerateV <- function(Y, Zminus, muZminus, covminus) {
    .Call('_GeneErrorMis_ZI_GenerateV', PACKAGE = 'GeneErrorMis', Y, Zminus, muZminus, covminus)
}

